### ISSUE TITLE
Stake amount of 0 missing on Registration pop up.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/airclaim_frontend_qa5#1]
1/6/22 AirClaim 1.1.1 Frontend enhancements Env: QA5 v0.5.11a-qa5 5 Link: https://tjrhs-gqaaa-aaaad-qa24a-cai.raw.ic0.app/
On the 'Registration' pop up, sentence "Verified accounts stake XPR"- stake amount of 0 missing. Expecting "Verified accounts stake 0XPR". 
![Freeos App 01-06-2022 13-25-26](https://user-images.githubusercontent.com/77765830/171310063-eb46f044-fdef-4c5e-9c91-6edb69275cbd.png)

**Comment by conorseed** [comment]
Interesting @judytan21! I haven't been able to replicate the issue on my end at QA5, or in my local testing environment.

The Registration popup shows "Verified accounts stake 0XPR" for me with multiple test users, including the test user you have used in your screenshot ("vincentvegan"). 

![Screen Shot 2022-06-01 at 2 03 45 PM](https://user-images.githubusercontent.com/13262289/171313326-e504e938-eb8d-4a8c-8619-6455c5773c1f.png)

Are you able to please confirm what browser you were using, as well as your operating system?

**Comment by judytan21** [comment]
Indeed. Running on mac using chrome. What about you?

**Comment by judytan21** [comment]
1/6/22 @ 2:37pm just replicated it.
<img width="505" alt="Screen Shot 2022-06-01 at 2 36 46 PM" src="https://user-images.githubusercontent.com/77765830/171316530-871d77c5-99e3-49af-a877-80549a32a821.png">

**Comment by conorseed** [comment]
I'm on a Mac and using Chrome, Brave and Safari. Can you please confirm the steps you took to replicate the issue, including the user you logged in with?

**Comment by judytan21** [comment]
1/6/22 Retest after clearing cache. Stake amount showing as 0XPR. Fixed
<img width="505" alt="Screen Shot 2022-06-01 at 3 19 00 PM" src="https://user-images.githubusercontent.com/77765830/171321223-3b978296-bd62-4f61-a5aa-5d46c75b5836.png">
.
