### ISSUE TITLE
Word misspelt in re-registration confirmation message.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/airclaim_frontend_qa5#2]
1/6/22 AirClaim 1.1.1 Frontend enhancements Env: QA5 v0.5.11a-qa5 5 Link: https://tjrhs-gqaaa-aaaad-qa24a-cai.raw.ic0.app/
Re-registration confirmation message, word 'successfully" misspelt as 'successfuly'.

<img width="449" alt="Screen Shot 2022-06-01 at 2 06 12 PM" src="https://user-images.githubusercontent.com/77765830/171313807-adc48506-51ec-42bb-9237-e3a6ab03fc18.png">
.

**Comment by conorseed** [comment]
Fixed with this commit here: [https://github.com/FreeosDAO/airclaim_frontend/commit/57302d9a69418149247d8e48f4a1a3845c566f33](https://github.com/FreeosDAO/airclaim_frontend/commit/57302d9a69418149247d8e48f4a1a3845c566f33)

**Comment by judytan21** [comment]
7/6/22 Retested in AirClaim 1.1.1 Frontend enhancements Env: QA5 v0.5.11c-qa5. Fixed.
